wip; cleanup tests

diff --git a/dependency/test/run-test b/dependency/test/run-test
--- a/dependency/test/run-test
+++ b/dependency/test/run-test
@@ -1,184 +1,49 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
-set -x
-
-# parent_dir="$(cd "$(dirname "$0")" && pwd)"
-
-# extract_tarball() {
-#   rm -rf nginx
-#   mkdir nginx
-#   tar -xf /tarball_path/nginx-1.22.0-bionic-paketo.tgz
-#   ls -lah
-# }
-
-# check_version() {
-#   expected_version=$1
-#   actual_version="$(./nginx/sbin/nginx -v 2>&1 | cut -d'/' -f2)"
-#   if [[ "${actual_version}" != "${expected_version}" ]]; then
-#     echo "Version ${actual_version} does not match expected version ${expected_version}"
-#     exit 1
-#   fi
-# }
-
-# check_server() {
-#   chmod 0755 nginx
-#   mkdir -p nginx/html
-#   cp "${parent_dir}/fixtures/nginx.conf" nginx/conf
-#   cp "${parent_dir}/fixtures/index.html" nginx/html
-
-#   ./nginx/sbin/nginx -p nginx
-
-#   set +e
-
-#   succeeded=0
-#   for _ in {1..5}; do
-#     response="$(curl -s http://localhost:8080)"
-#     if [[ $response == *"Sample nginx app"* ]]; then
-#       succeeded=1
-#       break
-#     fi
-#     sleep 1
-#   done
-
-#   kill "$(cat nginx/logs/nginx.pid)"
-
-#   set -e
-
-#   if [[ ${succeeded} -eq 0 ]]; then
-#     echo "Failed to curl server"
-#     exit 1
-#   fi
-# }
-
-# main() {
-#   extract_tarball
-#   check_version "$1"
-#   check_server
-
-#   echo "All tests passed!"
-# }
-
-# main "$@"
-
-
-# MOD ------------------------------------------------------------------------------------------------------------------------------------
-
-# parent_dir="$(cd "$(dirname "$0")" && pwd)"
-
-# extract_tarball() {
-#   rm -rf nginx
-#   mkdir nginx
-#   rm -rf dep-temp
-#   mkdir dep-temp
-#   tar -xf tarball_path/nginx-1.22.0-bionic.tgz -C dep-temp
-#   cp -R dep-temp/nginx/* nginx/
-#   ls -lah nginx/
-# }
-
-# check_version() {
-#   expected_version=$1
-#   actual_version="$(./nginx/sbin/nginx -v 2>&1 | cut -d'/' -f2)"
-#   if [[ "${actual_version}" != "${expected_version}" ]]; then
-#     echo "Version ${actual_version} does not match expected version ${expected_version}"
-#     exit 1
-#   fi
-# }
-
-# check_server() {
-#   chmod 0755 nginx
-#   mkdir -p nginx/html
-#   cp "${parent_dir}/fixtures/nginx.conf" nginx/conf
-#   cp "${parent_dir}/fixtures/index.html" nginx/html
-
-#   ./nginx/sbin/nginx -p nginx
-
-#   set +e
-
-#   succeeded=0
-#   for _ in {1..5}; do
-#     response="$(curl -s http://localhost:8080)"
-#     if [[ $response == *"Sample nginx app"* ]]; then
-#       succeeded=1
-#       break
-#     fi
-#     sleep 1
-#   done
-
-#   kill "$(cat nginx/logs/nginx.pid)"
-
-#   set -e
-
-#   if [[ ${succeeded} -eq 0 ]]; then
-#     echo "Failed to curl server"
-#     exit 1
-#   fi
-# }
-
-# main() {
-#   extract_tarball
-#   check_version "$1"
-#   check_server
-
-#   echo "All tests passed!"
-# }
-
-# main "$@"
-
-# ORIGINAL ------------------------------------------------------------------------------------------------------------------------------------
-parent_dir="$(cd "$(dirname "$0")" && pwd)"
-
-extract_tarball() {
-  rm -rf nginx
-  mkdir nginx
-  tar -xf tarball_path/nginx-1.22.0-bionic-paketo.tgz -C nginx
-}
-
-check_version() {
-  expected_version=$1
-  actual_version="$(./nginx/sbin/nginx -v 2>&1 | cut -d'/' -f2)"
-  if [[ "${actual_version}" != "${expected_version}" ]]; then
-    echo "Version ${actual_version} does not match expected version ${expected_version}"
-    exit 1
-  fi
-}
-
-check_server() {
-  chmod 0755 nginx
-  mkdir -p nginx/html
-  cp "${parent_dir}/fixtures/nginx.conf" nginx/conf
-  cp "${parent_dir}/fixtures/index.html" nginx/html
-
-  ./nginx/sbin/nginx -p nginx
-
-  set +e
-
-  succeeded=0
-  for _ in {1..5}; do
-    response="$(curl -s http://localhost:8080)"
-    if [[ $response == *"Sample nginx app"* ]]; then
-      succeeded=1
-      break
-    fi
-    sleep 1
-  done
-
-  kill "$(cat nginx/logs/nginx.pid)"
-
-  set -e
-
-  if [[ ${succeeded} -eq 0 ]]; then
-    echo "Failed to curl server"
-    exit 1
-  fi
-}
 
 main() {
-  extract_tarball
-  check_version "$1"
-  check_server
+  local tarball_path version
+  tarball_path=
+  version=
 
-  echo "All tests passed!"
+  while [ "${#}" != 0 ]; do
+    case "${1}" in
+      --version)
+        version="${2}"
+        shift 2
+        ;;
+
+      --tarballPath)
+        tarball_path="${2}"
+        shift 2
+        ;;
+
+      "")
+        shift
+        ;;
+
+      *)
+        echo "unknown argument \"${1}\""
+        exit 1
+    esac
+  done
+
+  if [[ "${version}" == "" || "${tarball_path}" == "" ]]; then
+    echo "version and tarballPath are required required"
+    exit 1
+  fi
+
+  if [[ $(basename -- ${tarball_path}) == *"bionic"* ]]; then
+    echo "Running bionic test..."
+    docker build -t test -f bionic/Dockerfile bionic/
+    docker run --rm -v "$(dirname -- ${tarball_path}):/tarball_path" test --version "${version}"
+  elif [[ $(basename -- ${tarball_path}) == *"jammy"* ]]; then
+    echo "Running jammy test..."
+    docker build -t test -f jammy/Dockerfile jammy/
+    docker run --rm -v "$(dirname -- ${tarball_path}):/tarball_path" test --version "${version}"
+  fi
+
 }
 
-main "$@"
+main "${@:-}"
